-- Admin allowlist -------------------------------------------------------
create table if not exists public.app_admins (
  email text primary key
);
alter table public.app_admins enable row level security;
insert into public.app_admins (email) values ('vikil.chandrapati1@gmail.com')
on conflict do nothing;

create or replace function public.is_admin()
returns boolean
language sql stable security definer
set search_path = public
as $$
  select exists (
    select 1 from public.app_admins
    where lower(email) = lower(coalesce(auth.jwt() ->> 'email', ''))
  );
$$;
revoke all on function public.is_admin() from public, anon;
grant execute on function public.is_admin() to authenticated;

-- Drop old permissive (public/anon) policies ----------------------------
drop policy if exists supplier_select_all on public.supplier;
drop policy if exists supplier_insert_all on public.supplier;
drop policy if exists supplier_product_select_all on public.supplier_product;
drop policy if exists upload_select_all on public.upload;
drop policy if exists upload_insert_all on public.upload;
drop policy if exists projects_select_all on public.projects;
drop policy if exists projects_insert_all on public.projects;
drop policy if exists projects_update_all on public.projects;
drop policy if exists projects_delete_all on public.projects;
drop policy if exists project_subtasks_select_all on public.project_subtasks;
drop policy if exists project_subtasks_insert_all on public.project_subtasks;
drop policy if exists project_subtasks_update_all on public.project_subtasks;
drop policy if exists project_subtasks_delete_all on public.project_subtasks;

-- New policies: authenticated read, admin write -------------------------
create policy supplier_select_auth on public.supplier
  for select to authenticated using (true);
create policy supplier_insert_admin on public.supplier
  for insert to authenticated with check (public.is_admin());
create policy supplier_update_admin on public.supplier
  for update to authenticated using (public.is_admin()) with check (public.is_admin());

create policy supplier_product_select_auth on public.supplier_product
  for select to authenticated using (true);
-- writes to supplier_product happen only inside finalize_ingest (security definer)

create policy upload_select_admin on public.upload
  for select to authenticated using (public.is_admin());
create policy upload_insert_admin on public.upload
  for insert to authenticated with check (public.is_admin());
create policy upload_update_admin on public.upload
  for update to authenticated using (public.is_admin()) with check (public.is_admin());

create policy projects_all_auth on public.projects
  for all to authenticated using (true) with check (true);
create policy project_subtasks_all_auth on public.project_subtasks
  for all to authenticated using (true) with check (true);

-- Staging table for chunked client-side ingest --------------------------
create table if not exists public.ingest_staging (
  staging_id bigint generated by default as identity primary key,
  upload_id integer not null references public.upload(upload_id) on delete cascade,
  supplier_id integer not null references public.supplier(supplier_id),
  supplier_sku text not null,
  supplier_description text,
  brand text,
  mpn text,
  price_ex_gst numeric not null default 0 check (price_ex_gst >= 0),
  effective_from date,
  is_active boolean not null default true
);
create index if not exists idx_ingest_staging_upload on public.ingest_staging (upload_id);
alter table public.ingest_staging enable row level security;
create policy ingest_staging_admin_all on public.ingest_staging
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- Atomic swap: replaces a supplier's catalogue from staged rows ---------
create or replace function public.finalize_ingest(p_upload_id integer)
returns jsonb
language plpgsql security definer
set search_path = public
as $$
declare
  v_supplier_id integer;
  v_staged integer;
  v_count integer;
begin
  if not public.is_admin() then
    raise exception 'not authorized';
  end if;

  select supplier_id into v_supplier_id
  from public.upload where upload_id = p_upload_id;
  if v_supplier_id is null then
    raise exception 'upload % not found', p_upload_id;
  end if;

  select count(*) into v_staged
  from public.ingest_staging where upload_id = p_upload_id;
  if v_staged = 0 then
    raise exception 'no staged rows for upload %', p_upload_id;
  end if;

  delete from public.supplier_product where supplier_id = v_supplier_id;

  insert into public.supplier_product
    (supplier_id, supplier_sku, supplier_description, brand, mpn, price_ex_gst, effective_from, is_active)
  select distinct on (supplier_sku)
    supplier_id, supplier_sku, supplier_description, brand, mpn, price_ex_gst, effective_from, is_active
  from public.ingest_staging
  where upload_id = p_upload_id
  order by supplier_sku, staging_id;

  get diagnostics v_count = row_count;

  delete from public.ingest_staging where upload_id = p_upload_id;

  update public.upload
     set parsed_ok = true,
         row_count = v_count,
         errors = jsonb_build_object('inserted', v_count, 'staged', v_staged)
   where upload_id = p_upload_id;

  return jsonb_build_object('inserted', v_count, 'staged', v_staged);
end;
$$;
revoke all on function public.finalize_ingest(integer) from public, anon;
grant execute on function public.finalize_ingest(integer) to authenticated;

-- Lock down existing RPC and tidy duplicate index -----------------------
revoke execute on function public.distinct_brands_for_supplier(integer) from anon, public;
grant execute on function public.distinct_brands_for_supplier(integer) to authenticated;

drop index if exists public.uq_supplier_sku_per_supplier;
